import localFont from "next/font/local";
import "./globals.css";

// Font files can be colocated inside of `app`
const myFont = localFont({
  src: "./Kallisto Light.otf",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Suspense } from "react";
// general components
import Nav from "@/components/nav/Nav";
import Footer from "@/components/footer/Footer";
import Loading from "@/components/loading/Loading";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Nav />
        <div className="mx-[30px]">
          <Suspense fallback={<Loading />}>{children} </Suspense>
        </div>
        <Footer />
      </body>
    </html>
  );
}
